[[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
    # [menu.main.params]  <-- 删掉或注释掉这两行
    #     icon = "home"

[[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
    # [menu.main.params]  <-- 删掉或注释掉这两行
    #     icon = "archive"

[[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 3
    # [menu.main.params]  <-- 删掉或注释掉这两行
    #     icon = "search"