baseURL = 'https://easyatm.github.io/blog/'
languageCode = 'zh-cn'
title = '我的极客空间'
theme = 'hugo-theme-stack'

[params]
    mainSections = ["post"]

    [params.sidebar]
        avatar = "https://github.com/easyatm.png"
        title = "EasyATM"
        subtitle = "极客、开发者、生活记录"

# 这里的链接要和上面创建的文件夹对应
[[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
    params:
        icon: home

[[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
    params:
        icon: archive

[[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 3
    params:
        icon: search